image: maven:3.9.11-amazoncorretto-25

build:
  script:
    - mvn -B -ntp clean verify

test:
  stage: test
  script:
    - apt-get update && apt-get install -y xvfb  
    - xvfb-run -a mvn test                       