package server.Service;

import commons.Recipe;
import commons.RecipeIngredient;
import commons.RecipeStep;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import server.Repository.RecipeRepository;
import java.util.List;

/**
 * Business‑logic layer for {@link Recipe} objects.
 *
 * <p>This service sits between the controller and the repository. It
 * validates input, translates repository exceptions into Spring Web
 * {@link ResponseStatusException}s, and exposes a clean API that the
 * {@code @RestController} can call.</p>
 *
 * <p>All methods are stateless except for the injected
 * {@link RecipeRepository}. The class is annotated with
 * {@code @Service} so Spring will automatically detect it during component
 * scanning and inject the required repository bean.</p>
 */
@Service
public class RecipeService {
    private final RecipeRepository recipeRepository;

    /**
     * Constructs a new {@code RecipeService}.
     *
     * @param recipeRepository the JPA repository for recipes
     */
    @Autowired
    public RecipeService(RecipeRepository recipeRepository) {
        this.recipeRepository = recipeRepository;
    }

    /**
     * Persists a new {@link Recipe} to the database.
     *
     * <p>Before saving, the method ensures that the title is neither
     * {@code null} nor an empty string. If validation fails, a
     * {@link ResponseStatusException} with HTTP status 400 (Bad Request)
     * is thrown so the controller can return an appropriate error to the
     * client.</p>
     *
     * @param recipe the recipe to add; must not be {@code null}
     * @return the persisted recipe, including any autogenerated ID
     * @throws ResponseStatusException if the title is empty or {@code null}
     */
    public Recipe addRecipe(Recipe recipe) {
        if (isNullOrEmpty(recipe.getTitle())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Recipe title cannot be empty");
        } else {
            return recipeRepository.save(recipe);
        }
    }

    /**
     * Retrieves a single {@link Recipe} by its primary key.
     *
     * @param id the identifier of the recipe to fetch
     * @return the matching recipe
     * @throws ResponseStatusException if no recipe with that ID exists
     */
    public Recipe getRecipe(long id) {
        return recipeRepository
                .findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND));
    }

    /**
     * Returns all recipes stored in the database.
     *
     * @return a {@link List} of every recipe; never {@code null}
     */
    public List<Recipe> getAllRecipes() {
        return recipeRepository.findAll();
    }

    /**
     * Deletes the recipe with the specified ID.
     *
     * <p>If the recipe does not exist, a {@code 404 Not Found} exception
     * is thrown. Otherwise, the repository deletes the record.</p>
     *
     * @param id the identifier of the recipe to remove
     * @throws ResponseStatusException if no recipe with that ID exists
     */
    public void removeRecipe(Long id) {
        if (recipeRepository.existsById(id)) {
            recipeRepository.deleteById(id);
        } else {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        }
    }

    /**
     * creates a copy of a recipe
     * @param id the id of the recipe to be cloned
     * @param name new name for the cloned recipe
     * @return the cloned recipe with a new name
     */
    public Recipe cloneRecipe(long id, String name) {
        Recipe recipe = getRecipe(id);
        Recipe cloneRecipe = new Recipe();
        String title;

        if (isNullOrEmpty(name)) {
            title = recipe.getTitle() + " Copy";
        }
        else {
            title = name;
        }

        cloneRecipe.setTitle(title);
        cloneRecipe.setIngredients(recipe.getIngredients());
        cloneRecipe.setSteps(recipe.getSteps());
        return recipeRepository.save(cloneRecipe);
    }


    /**
     * Creates a printable version of a recipe
     * @param id the id of the recipe to be printed
     * @return printable text from recipe
     */
    public String getPrintableRecipe(long id) {
        Recipe recipe = getRecipe(id);

        StringBuilder sb = new StringBuilder();
        sb.append(recipe.getTitle()).append("\n");

        sb.append("Ingredients:\n");
        if (recipe.getIngredients() != null) {
            for (RecipeIngredient ingredient : recipe.getIngredients()) {
                sb.append(" - ").append(ingredient).append("\n");
            }
        }

        sb.append("Steps:\n");
        if (recipe.getSteps() != null) {
            int i = 0;
            for (RecipeStep recipeStep : recipe.getSteps()) {
                sb.append(i++).append(". ").append(recipeStep).append("\n");
            }
        }

        return sb.toString();
    }

    /**
     * checks if string is empty or null
     * @param s string
     * @return boolean
     */
    private static boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }

}
