package server.Service;

import commons.Recipe;
import commons.RecipeIngredient;
import commons.RecipeStep;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;
import server.Repository.RecipeRepository;
import server.ws.WebSocketService;

import java.util.ArrayList;
import java.util.List;

/**
 * Business-logic layer for {@link Recipe} objects.
 *
 * <p>This service sits between the controller and the repository. It
 * validates input, translates repository exceptions into Spring Web
 * {@link ResponseStatusException}s, and exposes a clean API that the
 * {@code @RestController} can call.</p>
 *
 * <p>All methods are stateless except for the injected
 * {@link RecipeRepository}. The class is annotated with
 * {@code @Service} so Spring will automatically detect it during component
 * scanning and inject the required repository bean.</p>
 */
@Service
public class RecipeService {

    private final RecipeRepository recipeRepository;
    private final WebSocketService webSocketService;

    /**
     * Constructs a new {@code RecipeService}.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeRepository the JPA repository for recipes
     * @param webSocketService the WebSocket service for publishing events
     */
    @Autowired
    public RecipeService(RecipeRepository recipeRepository, WebSocketService webSocketService) {
        this.recipeRepository = recipeRepository;
        this.webSocketService = webSocketService;
    }

    /**
     * Persists a new {@link Recipe} to the database.
     *
     * <p>Before saving, the method ensures that the title is neither
     * {@code null} nor an empty string. If validation fails, a
     * {@link ResponseStatusException} with HTTP status 400 (Bad Request)
     * is thrown so the controller can return an appropriate error to the
     * client.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipe the recipe to add; must not be {@code null}
     * @return the persisted recipe, including any autogenerated ID
     * @throws ResponseStatusException if the title is empty or {@code null}
     */
    public Recipe addRecipe(Recipe recipe) {
        if (isNullOrEmpty(recipe.getTitle())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Recipe title cannot be empty");
        } else {
            Recipe saved = recipeRepository.save(recipe);
            webSocketService.publishRecipeListChange(saved.getId());
            webSocketService.publishRecipeChanged("Create", saved.getId(), saved.getTitle());
            return saved;
        }
    }

    /**
     * Retrieves a single {@link Recipe} by its primary key.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param id the identifier of the recipe to fetch
     * @return the matching recipe
     * @throws ResponseStatusException if no recipe with that ID exists
     */
    public Recipe getRecipe(Long id) {
        return findRecipe(id);
    }

    /**
     * Returns all recipes stored in the database.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @return a {@link List} of every recipe; never {@code null}
     */
    public List<Recipe> getAllRecipes() {
        return recipeRepository.findAll();
    }

    /**
     * Deletes the recipe with the specified ID.
     *
     * <p>If the recipe does not exist, a {@code 404 Not Found} exception
     * is thrown. Otherwise, the repository deletes the record.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param id the identifier of the recipe to remove
     * @throws ResponseStatusException if no recipe with that ID exists
     */
    public void removeRecipe(Long id) {
        if (recipeRepository.existsById(id)) {
            recipeRepository.deleteById(id);
            webSocketService.publishRecipeListChange(id);
            webSocketService.publishRecipeChanged("Deleted", id, null);
        } else {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND);
        }
        recipeRepository.deleteById(id);
    }

    /**
     * Updates an existing {@link Recipe}.
     *
     * <p>This method validates that the recipe has a non-empty title and that
     * it already exists in the database before saving the changes.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipe the recipe to update; must not be {@code null}
     * @return the updated recipe as persisted by the repository
     * @throws ResponseStatusException if the
     * title is empty or {@code null}, or if the recipe does not exist
     */
    public Recipe updateRecipe(Recipe recipe) {
        if (isNullOrEmpty(recipe.getTitle()) || !recipeRepository.existsById(recipe.getId())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Recipe title cannot be empty");
        } else {
            Recipe saved = recipeRepository.save(recipe);
            webSocketService.publishRecipeChanged("Changed", saved.getId(), saved.getTitle());
            return saved;
        }
    }

    /**
     * Adds a {@link RecipeIngredient} to an existing {@link Recipe}.
     *
     * <p>If the ingredient is already present in the recipe, a
     * {@link ResponseStatusException} with HTTP status 400 (Bad Request) is thrown.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId         the id of the recipe to which the ingredient is added
     * @param recipeIngredient the recipe ingredient to add; must not be {@code null}
     * @return the updated recipe after the ingredient has been added
     * @throws ResponseStatusException if the recipe
     * does not exist or the ingredient already exists in the recipe
     */
    public Recipe addIngredientToRecipe(long recipeId, RecipeIngredient recipeIngredient) {
        Recipe recipe = findRecipe(recipeId);

        if (recipe.getIngredients().contains(recipeIngredient)) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST,
                    "Recipe ingredient already exists"
            );
        }

        recipeIngredient.setRecipe(recipe);
        recipe.addRecipeIngredient(recipeIngredient);

        Recipe saved = recipeRepository.save(recipe);
        webSocketService.publishRecipeContentChanged(recipeId);
        return saved;
    }

    /**
     * Adds a {@link RecipeStep} to an existing {@link Recipe}.
     *
     * <p>The step is associated with the recipe and appended to its list of steps
     * before the recipe is saved.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId   the id of the recipe to which the step is added
     * @param recipeStep the recipe step to add; must not be {@code null}
     * @return the updated recipe after the step has been added
     * @throws ResponseStatusException if the recipe does not exist
     */
    public Recipe addStepToRecipe(long recipeId, RecipeStep recipeStep) {
        Recipe recipe = findRecipe(recipeId);

        recipeStep.setRecipe(recipe);
        recipe.addStep(recipeStep);
        Recipe saved = recipeRepository.save(recipe);
        webSocketService.publishRecipeContentChanged(recipeId);
        return saved;
    }

    /**
     * Removes a specific {@link RecipeIngredient} instance from a recipe.
     *
     * <p>The given ingredient is removed from the recipe's ingredient collection
     * and the updated recipe is persisted.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId         the id of the recipe from which the ingredient is removed
     * @param recipeIngredient the ingredient instance to remove; must not be {@code null}
     * @return the updated recipe after the ingredient has been removed
     * @throws ResponseStatusException if the recipe does not exist
     */
    public Recipe deleteIngredientFromRecipe(long recipeId, RecipeIngredient recipeIngredient) {
        Recipe recipe = findRecipe(recipeId);
        recipe.getIngredients().remove(recipeIngredient);
        Recipe saved = recipeRepository.save(recipe);
        webSocketService.publishRecipeContentChanged(recipeId);
        return saved;
    }

    /**
     * Removes a specific {@link RecipeStep} instance from a recipe.
     *
     * <p>The given step is removed from the recipe's step collection
     * and the updated recipe is persisted.</p>
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId   the id of the recipe from which the step is removed
     * @param recipeStep the step instance to remove; must not be {@code null}
     * @return the updated recipe after the step has been removed
     * @throws ResponseStatusException if the recipe does not exist
     */
    public Recipe deleteStepFromRecipe(long recipeId, RecipeStep recipeStep) {
        Recipe recipe = findRecipe(recipeId);
        recipe.getSteps().remove(recipeStep);
        Recipe saved = recipeRepository.save(recipe);
        webSocketService.publishRecipeContentChanged(recipeId);
        return saved;
    }

    //AI-generated
    /**
     * Updates a single {@link RecipeStep} of a given recipe.
     *
     * <p>Finds the target step by {@code stepId} inside the recipe identified by {@code recipeId},
     * applies the provided changes (position and/or instruction), and persists via the recipe
     * aggregate so JPA cascading updates the child entity.</p>
     *
     * @param recipeId the id of the parent {@link Recipe}
     * @param stepId   the id of the {@link RecipeStep} to update
     * @param patch    a {@link RecipeStep} carrying the new values
     * @return the updated {@link RecipeStep}
     * @throws org.springframework.web.server.ResponseStatusException
     *         {@code 404 NOT_FOUND} if the recipe or step cannot be found
     */
    public RecipeStep updateStepInRecipe(Long recipeId, Long stepId, RecipeStep patch) {
        Recipe recipe = getRecipe(recipeId);
        RecipeStep target = recipe.getSteps().stream()
                .filter(s -> s.getId() != null && s.getId().equals(stepId))
                .findFirst()
                .orElseThrow(() ->
                        new ResponseStatusException(HttpStatus.NOT_FOUND, "Step not found"));

        if (patch.getInstruction() != null) {
            target.setInstruction(patch.getInstruction());
        }
        target.setPosition(patch.getPosition());

        recipeRepository.save(recipe); // cascade updates the step
        webSocketService.publishRecipeContentChanged(recipeId);
        return target;
    }

    /**
     * Returns all recipe ingredients belonging to the given recipe.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId the id of the recipe
     * @return a list of recipe ingredients for the recipe
     * @throws ResponseStatusException if no recipe with the given id exists
     */
    public List<RecipeIngredient> getIngredientsForRecipe(long recipeId) {
        Recipe recipe = getRecipe(recipeId);
        return new ArrayList<>(recipe.getIngredients());
    }

    /**
     * Returns all steps belonging to the given recipe.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId the id of the recipe
     * @return a list of recipe steps for the recipe
     * @throws ResponseStatusException if no recipe with the given id exists
     */
    public List<RecipeStep> getStepsForRecipe(long recipeId) {
        Recipe recipe = getRecipe(recipeId);
        return new ArrayList<>(recipe.getSteps());
    }
    
    /**
     * Removes a recipe ingredient from a recipe by its id.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId           the id of the recipe
     * @param recipeIngredientId the id of the recipe ingredient to remove
     * @return the updated recipe
     * @throws ResponseStatusException if no recipe with the given id exists
     */
    public Recipe removeIngredientFromRecipe(long recipeId, long recipeIngredientId) {
        Recipe recipe = getRecipe(recipeId);
        recipe.getIngredients().removeIf(ingredient ->
                ingredient.getId() != null && ingredient.getId().equals(recipeIngredientId));
        Recipe saved = recipeRepository.save(recipe);
        webSocketService.publishRecipeContentChanged(recipeId);
        return saved;
    }

    /**
     * Removes a step from a recipe by its id.
     *
     * <p><em>Note: This Javadoc was AI-generated.</em></p>
     *
     * @param recipeId the id of the recipe
     * @param stepId   the id of the step to remove
     * @return the updated recipe
     * @throws ResponseStatusException if no recipe with the given id exists
     */
    public Recipe removeStepFromRecipe(long recipeId, long stepId) {
        Recipe recipe = getRecipe(recipeId);
        recipe.getSteps().removeIf(step ->
                step.getId() != null && step.getId().equals(stepId));
        Recipe saved = recipeRepository.save(recipe);
        webSocketService.publishRecipeContentChanged(recipeId);
        return saved;
    }

    /**
     * Finds a {@link Recipe} by its ID.
     *
     * @param recipeId the ID of the recipe to find
     * @return the {@link Recipe} with the given ID
     * @throws ResponseStatusException if no recipe is found (HTTP 404)
     */
    private Recipe findRecipe(long recipeId) {
        return recipeRepository.findById(recipeId)
                .orElseThrow(() ->
                        new ResponseStatusException(HttpStatus.NOT_FOUND));
    }

    /**
     * checks if string is empty or null
     * @param s string
     * @return boolean
     */
    private static boolean isNullOrEmpty(String s) {
        return s == null || s.isEmpty();
    }
}
