/*
 * Copyright 2021 Delft University of Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package client.utils;

import static jakarta.ws.rs.core.MediaType.APPLICATION_JSON;


import java.net.ConnectException;
import java.util.List;

import commons.Recipe;
import org.glassfish.jersey.client.ClientConfig;

import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.core.GenericType;

/**
 * Utility class that encapsulates all HTTP communication with the
 * backend REST API.
 */
public class ServerUtils {

    private static final String SERVER = "http://localhost:8080/";

    /**
     * Retrieves all {@link Recipe} objects from the server.
     *
     * @return a {@code List<Recipe>} containing every recipe stored on the
     *         backend. The list is never {@code null}, but may be empty if no
     *         recipes exist.
     */
    public List<Recipe> getRecipes() {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<Recipe>>() {});
    }

    /**
     * Persists a new {@link Recipe} on the server.
     *
     * @param recipe the {@code Recipe} instance to send; must not be {@code null}
     * @return the server‑side representation of the recipe, including any
     *         autogenerated fields (e.g., ID)
     */
    public Recipe addRecipe(Recipe recipe) {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe") //
                .request(APPLICATION_JSON) //
                .post(Entity.entity(recipe, APPLICATION_JSON), Recipe.class);
    }

    /**
     * Checks whether the backend server is reachable.
     *
     * <p>This method performs a lightweight {@code GET} request to the base
     * URL.  If the connection fails because the host cannot be reached,
     * the method returns {@code false}.  All other exceptions are ignored
     * and treated as a successful connection.</p>
     *
     * @return {@code true} if the server responds, {@code false} otherwise.
     */
    public boolean isServerAvailable() {
        try {
            ClientBuilder.newClient(new ClientConfig()) //
                    .target(SERVER) //
                    .request(APPLICATION_JSON) //
                    .get();
        } catch (ProcessingException e) {
            if (e.getCause() instanceof ConnectException) {
                return false;
            }
        }
        return true;
    }
}