package client.utils;

import static jakarta.ws.rs.core.MediaType.APPLICATION_JSON;


import java.net.ConnectException;
import java.util.List;

import commons.*;
import org.glassfish.jersey.client.ClientConfig;

import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.core.GenericType;

/**
 * Utility class that encapsulates all HTTP communication with the
 * backend REST API.
 */
public class ServerUtils {

    private static final String SERVER = "http://localhost:8080/";

    /**
     * Retrieves all {@link Recipe} objects from the server.
     *
     * @return a {@code List<Recipe>} containing every recipe stored on the
     *         backend. The list is never {@code null}, but may be empty if no
     *         recipes exist.
     */
    public List<Recipe> getRecipes() {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<Recipe>>() {});
    }

    /**
     * Persists a new {@link Recipe} on the server.
     *
     * @param recipe the {@code Recipe} instance to send; must not be {@code null}
     * @return the server‑side representation of the recipe, including any
     *         autogenerated fields (e.g., ID)
     */
    public Recipe addRecipe(Recipe recipe) {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe") //
                .request(APPLICATION_JSON) //
                .post(Entity.entity(recipe, APPLICATION_JSON), Recipe.class);
    }

    /**
     * Removes a {@link Recipe} instance from the server.
     *
     * @param recipe the {@code Recipe} instance to be removed; must not be {@code null}
     */
    public void deleteRecipe(Recipe recipe) {
        ClientBuilder.newClient(new ClientConfig())
                .target(SERVER).path("api/recipe/" + recipe.getId())
                .request(APPLICATION_JSON)
                .delete();
    }

    /**
     * Retrieves all {@link Ingredient} objects from the server.
     *
     * @return a {@code List<Ingredient>} containing every ingredient stored on the
     *         backend. The list is never {@code null}, but may be empty if no
     *         ingredients exist.
     */
    public List<Ingredient> getIngredients() {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/ingredient") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<Ingredient>>() {});
    }

    /**
     * Persists a new {@link Ingredient} on the server.
     *
     * @param ingredient the {@code Ingredient} instance to send; must not be {@code null}
     * @return the server‑side representation of the ingredient, including any
     *         autogenerated fields (e.g., ID)
     */
    public Ingredient addIngredient(Ingredient ingredient) {
        return ClientBuilder.newClient(new ClientConfig())
                .target(SERVER).path("api/ingredient")
                .request(APPLICATION_JSON)
                .post(Entity.entity(ingredient, APPLICATION_JSON), Ingredient.class);
    }

    /**
     * Removes a {@link Ingredient} instance from the server.
     *
     * @param ingredient the {@code Ingredient} instance to be removed; must not be {@code null}
     */
    public void deleteIngredient(Ingredient ingredient) {
        ClientBuilder.newClient(new ClientConfig())
                .target(SERVER).path("api/ingredient/" + ingredient.getId())
                .request(APPLICATION_JSON)
                .delete();
    }

    /**
     * Adds a new {@link RecipeStep} to a recipe on the server.
     *
     * @param recipeId the id of the target recipe
     * @param step the step payload (position, instruction)
     * @return the updated {@link Recipe} returned by the server
     */
    public Recipe addRecipeStep(Long recipeId, RecipeStep step) {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe/" + recipeId + "/steps") //
                .request(APPLICATION_JSON) //
                .post(Entity.entity(step, APPLICATION_JSON), Recipe.class);
    }

    /**
     * Retrieves all {@link RecipeStep} objects for a specific recipe.
     *
     * @param recipeId the id of the recipe whose steps are requested
     * @return a {@code List<RecipeStep>} containing all steps for the recipe;
     *         never {@code null}, but may be empty
     */
    public List<RecipeStep> getStepsForRecipe(Long recipeId) {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe/" + recipeId + "/steps") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<RecipeStep>>() {});
    }

    /**
     * Deletes a recipe step from a recipe on the server.
     *
     * @param recipeId the recipe ID
     * @param stepId the step ID to delete
     */
    public void deleteRecipeStep(Long recipeId, Long stepId) {
        ClientBuilder.newClient(new ClientConfig())
                .target(SERVER)
                .path("api/recipe/" + recipeId + "/steps/" + stepId)
                .request(APPLICATION_JSON)
                .delete();
    }

    /**
     * Updates an existing recipe step on the server.
     *
     * @param recipeId id of the recipe containing the step
     * @param step updated step data
     * @return the updated RecipeStep from the server
     */
    public RecipeStep updateRecipeStep(Long recipeId, RecipeStep step) {
        return ClientBuilder.newClient(new ClientConfig())
                .target(SERVER)
                .path("api/recipe/" + recipeId + "/steps")
                .request(APPLICATION_JSON)
                .post(Entity.entity(step, APPLICATION_JSON), RecipeStep.class);
    }

    /**
     * Checks whether the backend server is reachable.
     *
     * <p>This method performs a lightweight {@code GET} request to the base
     * URL.  If the connection fails because the host cannot be reached,
     * the method returns {@code false}.  All other exceptions are ignored
     * and treated as a successful connection.</p>
     *
     * @return {@code true} if the server responds, {@code false} otherwise.
     */
    public boolean isServerAvailable() {
        try {
            ClientBuilder.newClient(new ClientConfig()) //
                    .target(SERVER) //
                    .request(APPLICATION_JSON) //
                    .get();
        } catch (ProcessingException e) {
            if (e.getCause() instanceof ConnectException) {
                return false;
            }
        }
        return true;
    }
}