package client.utils;

import static jakarta.ws.rs.core.MediaType.APPLICATION_JSON;


import java.net.ConnectException;
import java.util.List;

import commons.Ingredient;
import commons.Recipe;
import commons.RecipeIngredient;
import org.glassfish.jersey.client.ClientConfig;

import jakarta.ws.rs.ProcessingException;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.core.GenericType;

/**
 * Utility class that encapsulates all HTTP communication with the
 * backend REST API.
 */
public class ServerUtils {

    private static final String SERVER = "http://localhost:8080/";

    /**
     * Retrieves all {@link Recipe} objects from the server.
     *
     * @return a {@code List<Recipe>} containing every recipe stored on the
     *         backend. The list is never {@code null}, but may be empty if no
     *         recipes exist.
     */
    public List<Recipe> getRecipes() {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<Recipe>>() {});
    }

    /**
     * Persists a new {@link Recipe} on the server.
     *
     * @param recipe the {@code Recipe} instance to send; must not be {@code null}
     * @return the server‑side representation of the recipe, including any
     *         autogenerated fields (e.g., ID)
     */
    public Recipe addRecipe(Recipe recipe) {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("api/recipe") //
                .request(APPLICATION_JSON) //
                .post(Entity.entity(recipe, APPLICATION_JSON), Recipe.class);
    }

    //TODO update the path once the backend is ready
    /**
     * Retrieves all {@link Ingredient} objects from the server.
     *
     * @return a list of ingredients; may be empty if none exist
     */
    public List<Ingredient> getIngredients() {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<Ingredient>>() {});
    }


    //TODO update the path wonce the backend is ready
    /**
     * Retrieves all {@link RecipeIngredient} entries for a specific recipe.
     *
     * @param recipeId the ID of the recipe to fetch ingredients for
     * @return a list of recipe-ingredient associations;
     */
    public List<RecipeIngredient> getIngredientsForRecipe(Long recipeId) {
        return ClientBuilder.newClient(new ClientConfig()) //
                .target(SERVER).path("") //
                .request(APPLICATION_JSON) //
                .get(new GenericType<List<RecipeIngredient>>() {});
    }

    /**
     * Checks whether the backend server is reachable.
     *
     * <p>This method performs a lightweight {@code GET} request to the base
     * URL.  If the connection fails because the host cannot be reached,
     * the method returns {@code false}.  All other exceptions are ignored
     * and treated as a successful connection.</p>
     *
     * @return {@code true} if the server responds, {@code false} otherwise.
     */
    public boolean isServerAvailable() {
        try {
            ClientBuilder.newClient(new ClientConfig()) //
                    .target(SERVER) //
                    .request(APPLICATION_JSON) //
                    .get();
        } catch (ProcessingException e) {
            if (e.getCause() instanceof ConnectException) {
                return false;
            }
        }
        return true;
    }
}